;; Shepherd Command Line Interface
;; Provides user-friendly command line commands for service management

(use-modules (ice-9 match)
             (ice-9 rdelim)
             (ice-9 format)
             (srfi srfi-1))

(use-module (shepherd))

;; Command definitions
(define (shepherd-command-help)
  "Display help information for shepherd commands."
  (display "Shepherd Process Management System - Command Line Interface\n")
  (display "\nUsage: shepherd <command> [options]\n")
  (display "\nAvailable commands:\n")
  (display "  help                Show this help message\n")
  (display "  start <service>     Start a service\n")
  (display "  stop <service>      Stop a service\n")
  (display "  restart <service>   Restart a service\n")
  (display "  reload <service>    Reload a service configuration\n")
  (display "  status <service>    Show service status\n")
  (display "  list                List all services\n")
  (display "  register <file>    Register services from a file\n")
  (display "  unregister <service> Unregister a service\n")
  (display "  daemon              Run the shepherd daemon\n")
  (display "  load-rc <file>      Load service definitions from a file\n")
  (display "  save-rc <file>      Save current service definitions to a file\n")
  (display "\n")
  (display "Service files should contain service definitions using make-service.\n")
  (display "Example: (make-service \"my-service\" \"Description\" my-service-proc)\n"))

(define (shepherd-command-start service-name)
  "Start a service by name."
  (let ((service (find (lambda (s) (string=? (service-name s) service-name)) 
                        service-registry)))
    (if service
        (begin
          (format #t "Starting service ~a...~%" service-name)
          (start-service service))
        (begin
          (format #t "Service '~a' not found~%" service-name)
          #f))))

(define (shepherd-command-stop service-name)
  "Stop a service by name."
  (let ((service (find (lambda (s) (string=? (service-name s) service-name)) 
                        service-registry)))
    (if service
        (begin
          (format #t "Stopping service ~a...~%" service-name)
          (stop-service service))
        (begin
          (format #t "Service '~a' not found~%" service-name)
          #f))))

(define (shepherd-command-restart service-name)
  "Restart a service by name."
  (let ((service (find (lambda (s) (string=? (service-name s) service-name)) 
                        service-registry)))
    (if service
        (begin
          (format #t "Restarting service ~a...~%" service-name)
          (restart-service service))
        (begin
          (format #t "Service '~a' not found~%" service-name)
          #f))))

(define (shepherd-command-reload service-name)
  "Reload a service by name."
  (let ((service (find (lambda (s) (string=? (service-name s) service-name)) 
                        service-registry)))
    (if service
        (begin
          (format #t "Reloading service ~a...~%" service-name)
          (reload-service service))
        (begin
          (format #t "Service '~a' not found~%" service-name)
          #f))))

(define (shepherd-command-status service-name)
  "Show status of a service by name."
  (status-service service-name))

(define (shepherd-command-list)
  "List all registered services."
  (list-services))

(define (shepherd-command-register file-path)
  "Register services from a file."
  (if (file-exists? file-path)
      (begin
        (format #t "Loading services from ~a...~%" file-path)
        (load file-path)
        (format #t "Services loaded successfully~%"))
      (begin
        (format #t "File '~a' not found~%" file-path)
        #f)))

(define (shepherd-command-unregister service-name)
  "Unregister a service by name."
  (let ((service (find (lambda (s) (string=? (service-name s) service-name)) 
                        service-registry)))
    (if service
        (begin
          (format #t "Unregistering service ~a...~%" service-name)
          (unregister-service service))
        (begin
          (format #t "Service '~a' not found~%" service-name)
          #f))))

(define (shepherd-command-daemon)
  "Run the shepherd daemon."
  (format #t "Starting shepherd daemon... Press Ctrl+C to exit~%")
  (run-shepherd))

(define (shepherd-command-load-rc file-path)
  "Load service definitions from a configuration file."
  (shepherd-command-register file-path))

(define (shepherd-command-save-rc file-path)
  "Save current service definitions to a file."
  (format #t "Saving service definitions to ~a...~%" file-path)
  (with-output-to-file file-path
    (lambda ()
      (display ";; Service Configuration File\n")
      (display ";; Generated by Shepherd System\n\n")
      (for-each (lambda (service)
                  (format #t "(register-service ~s)\n" service))
                service-registry)))
  (format #t "Service definitions saved successfully~%"))

;; Main command parser
(define (parse-args args)
  "Parse command line arguments."
  (match args
    (()
     'help)
    (("help" . _)
     'help)
    (("start" name . _)
     `(start ,name))
    (("stop" name . _)
     `(stop ,name))
    (("restart" name . _)
     `(restart ,name))
    (("reload" name . _)
     `(reload ,name))
    (("status" name . _)
     `(status ,name))
    (("list" . _)
     'list)
    (("register" file . _)
     `(register ,file))
    (("unregister" service . _)
     `(unregister ,service))
    (("daemon" . _)
     'daemon)
    (("load-rc" file . _)
     `(load-rc ,file))
    (("save-rc" file . _)
     `(save-rc ,file))
    (_
     (format #t "Unknown command: ~a~%" (car args))
     'help)))

;; Main entry point
(define (main args)
  "Main entry point for shepherd command line."
  (let ((command (parse-args args)))
    (match command
      ('help
       (shepherd-command-help))
      (('start name)
       (shepherd-command-start name))
      (('stop name)
       (shepherd-command-stop name))
      (('restart name)
       (shepherd-command-restart name))
      (('reload name)
       (shepherd-command-reload name))
      (('status name)
       (shepherd-command-status name))
      ('list
       (shepherd-command-list))
      (('register file)
       (shepherd-command-register file))
      (('unregister service)
       (shepherd-command-unregister service))
      ('daemon
       (shepherd-command-daemon))
      (('load-rc file)
       (shepherd-command-load-rc file))
      (('save-rc file)
       (shepherd-command-save-rc file))
      (_
       (format #t "Invalid command~%")))))

;; Entry point for standalone execution
(when (= 1 (length command-line-arguments))
  (main (cdr command-line-arguments)))