#ifndef KERNEL_COMPAT_LINUX_SYSCALL_H
#define KERNEL_COMPAT_LINUX_SYSCALL_H

#include <arch/types.h>

typedef struct {
    uint64_t st_dev;
    uint64_t st_ino;
    uint64_t st_nlink;
    uint32_t st_mode;
    uint32_t st_uid;
    uint32_t st_gid;
    uint64_t st_rdev;
    int64_t  st_size;
    int64_t  st_blksize;
    int64_t  st_blocks;
    int64_t  st_atime;
    int64_t  st_mtime;
    int64_t  st_ctime;
} linux_stat_t;

typedef struct {
    int64_t  f_bsize;
    int64_t  f_frsize;
    uint64_t f_blocks;
    uint64_t f_bfree;
    uint64_t f_bavail;
    uint64_t f_files;
    uint64_t f_ffree;
    uint64_t f_favail;
    uint64_t f_flag;
    uint64_t f_namemax;
} linux_statfs_t;

typedef struct {
    uint64_t d_ino;
    int64_t  d_off;
    uint16_t d_reclen;
    uint8_t  d_type;
    char     d_name[256];
} linux_dirent_t;

typedef struct {
    int32_t  si_signo;
    int32_t  si_errno;
    int32_t  si_code;
    int32_t  si_trapno;
    int32_t  si_pid;
    int32_t  si_uid;
    int32_t  si_status;
    void*    si_addr;
} linux_siginfo_t;

typedef struct {
    void*    ss_sp;
    uint32_t ss_flags;
    uint64_t ss_size;
} linux_stack_t;

typedef struct {
    uint64_t r8, r9, r10, r11, r12, r13, r14, r15;
    uint64_t rdi, rsi, rbp, rbx, rdx, rax, rcx, rsp;
    uint64_t rip;
    uint64_t eflags;
    uint16_t cs, ss, ds, es, fs, gs;
} linux_regs_t;

typedef struct {
    uint64_t utime;
    uint64_t stime;
    int64_t  cutime;
    int64_t  cstime;
} linux_rusage_t;

typedef struct {
    int32_t  clockid;
    uint32_t flags;
    uint64_t value;
    uint64_t interval;
} linux_timer_t;

long linux_sys_read(int fd, void* buf, uint64_t count);
long linux_sys_write(int fd, const void* buf, uint64_t count);
long linux_sys_open(const char* path, int flags, int mode);
long linux_sys_close(int fd);
long linux_sys_stat(const char* path, linux_stat_t* buf);
long linux_sys_fstat(int fd, linux_stat_t* buf);
long linux_sys_lstat(const char* path, linux_stat_t* buf);
long linux_sys_poll(void* fds, uint32_t nfds, int timeout);
long linux_sys_lseek(int fd, int64_t offset, int whence);
long linux_sys_mmap(void* addr, uint64_t len, int prot, int flags, int fd, int64_t off);
long linux_sys_mprotect(void* addr, uint64_t len, int prot);
long linux_sys_munmap(void* addr, uint64_t len);
long linux_sys_brk(void* addr);
long linux_sys_rt_sigaction(int signum, const void* act, void* oldact, uint64_t sigsetsize);
long linux_sys_rt_sigprocmask(int how, const void* set, void* oldset, uint64_t sigsetsize);
long linux_sys_ioctl(int fd, uint64_t cmd, void* arg);
long linux_sys_pread64(int fd, void* buf, uint64_t count, int64_t offset);
long linux_sys_pwrite64(int fd, const void* buf, uint64_t count, int64_t offset);
long linux_sys_readv(int fd, const void* iov, int iovcnt);
long linux_sys_writev(int fd, const void* iov, int iovcnt);
long linux_sys_access(const char* path, int mode);
long linux_sys_pipe(int* pipefd);
long linux_sys_select(int nfds, void* readfds, void* writefds, void* exceptfds, void* timeout);
long linux_sys_sched_yield(void);
long linux_sys_mremap(void* addr, uint64_t old_len, uint64_t new_len, int flags, void* new_addr);
long linux_sys_msync(void* addr, uint64_t len, int flags);
long linux_sys_mincore(void* addr, uint64_t len, void* vec);
long linux_sys_madvise(void* addr, uint64_t len, int advice);
long linux_sys_shmget(int key, uint64_t size, int flags);
long linux_sys_shmat(int shmid, const void* addr, int flags);
long linux_sys_shmctl(int shmid, int cmd, void* buf);
long linux_sys_dup(int fd);
long linux_sys_dup2(int oldfd, int newfd);
long linux_sys_pause(void);
long linux_sys_nanosleep(const void* req, void* rem);
long linux_sys_getitimer(int which, void* value);
long linux_sys_setitimer(int which, const void* value, void* ovalue);
long linux_sys_getpid(void);
long linux_sys_sendfile(int out_fd, int in_fd, int64_t* offset, uint64_t count);
long linux_sys_socket(int domain, int type, int protocol);
long linux_sys_connect(int fd, const void* addr, int addrlen);
long linux_sys_accept(int fd, void* addr, int* addrlen);
long linux_sys_sendto(int fd, const void* buf, uint64_t len, int flags, const void* addr, int addrlen);
long linux_sys_recvfrom(int fd, void* buf, uint64_t len, int flags, void* addr, int* addrlen);
long linux_sys_sendmsg(int fd, const void* msg, int flags);
long linux_sys_recvmsg(int fd, void* msg, int flags);
long linux_sys_shutdown(int fd, int how);
long linux_sys_bind(int fd, const void* addr, int addrlen);
long linux_sys_listen(int fd, int backlog);
long linux_sys_getsockname(int fd, void* addr, int* addrlen);
long linux_sys_getpeername(int fd, void* addr, int* addrlen);
long linux_sys_socketpair(int domain, int type, int protocol, int* sv);
long linux_sys_setsockopt(int fd, int level, int optname, const void* optval, int optlen);
long linux_sys_getsockopt(int fd, int level, int optname, void* optval, int* optlen);
long linux_sys_clone(uint64_t flags, void* stack, int* parent_tid, int* child_tid, uint64_t tls);
long linux_sys_fork(void);
long linux_sys_vfork(void);
long linux_sys_execve(const char* path, char* const* argv, char* const* envp);
long linux_sys_exit(int status);
long linux_sys_wait4(int pid, int* status, int options, void* rusage);
long linux_sys_kill(int pid, int sig);
long linux_sys_tkill(int tid, int sig);
long linux_sys_tgkill(int tgid, int tid, int sig);
long linux_sys_sigaltstack(const linux_stack_t* ss, linux_stack_t* old_ss);
long linux_sys_rt_sigsuspend(const void* mask, uint64_t sigsetsize);
long linux_sys_rt_sigpending(void* set, uint64_t sigsetsize);
long linux_sys_rt_sigtimedwait(const void* set, linux_siginfo_t* info, const void* timeout, uint64_t sigsetsize);
long linux_sys_getuid(void);
long linux_sys_geteuid(void);
long linux_sys_getgid(void);
long linux_sys_getegid(void);
long linux_sys_setuid(uid_t uid);
long linux_sys_setgid(gid_t gid);
long linux_sys_getresuid(uid_t* ruid, uid_t* euid, uid_t* suid);
long linux_sys_getresgid(gid_t* rgid, gid_t* egid, gid_t* sgid);
long linux_sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
long linux_sys_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
long linux_sys_setpgid(int pid, int pgid);
long linux_sys_getpgid(int pid);
long linux_sys_getppid(void);
long linux_sys_getsid(int pid);
long linux_sys_setsid(void);
long linux_sys_getgroups(int size, gid_t* list);
long linux_sys_setgroups(int size, const gid_t* list);
long linux_sys_umask(int mask);
long linux_sys_chmod(const char* path, int mode);
long linux_sys_fchmod(int fd, int mode);
long linux_sys_chown(const char* path, uid_t uid, gid_t gid);
long linux_sys_fchown(int fd, uid_t uid, gid_t gid);
long linux_sys_lchown(const char* path, uid_t uid, gid_t gid);
long linux_sys_chroot(const char* path);
long linux_sys_pivot_root(const char* new_root, const char* put_old);
long linux_sys_mkdir(const char* path, int mode);
long linux_sys_rmdir(const char* path);
long linux_sys_unlink(const char* path);
long linux_sys_symlink(const char* target, const char* linkpath);
long linux_sys_readlink(const char* path, char* buf, uint64_t bufsiz);
long linux_sys_link(const char* oldpath, const char* newpath);
long linux_sys_rename(const char* oldpath, const char* newpath);
long linux_sys_getcwd(char* buf, uint64_t size);
long linux_sys_mount(const char* src, const char* tgt, const char* type, uint64_t flags, const void* data);
long linux_sys_umount2(const char* tgt, int flags);
long linux_sys_truncate(const char* path, int64_t length);
long linux_sys_ftruncate(int fd, int64_t length);
long linux_sys_sync(void);
long linux_sys_fsync(int fd);
long linux_sys_fdatasync(int fd);
long linux_sys_acct(const char* path);
long linux_sys_getdents64(int fd, linux_dirent_t* dirp, uint64_t count);
long linux_sys_fcntl(int fd, int cmd, uint64_t arg);
long linux_sys_flock(int fd, int cmd);
long linux_sys_fadvise64(int fd, int64_t offset, int64_t len, int advice);
long linux_sys_getrlimit(int resource, void* rlim);
long linux_sys_setrlimit(int resource, const void* rlim);
long linux_sys_prlimit64(int pid, int resource, const void* new_limit, void* old_limit);
long linux_sys_getrusage(int who, linux_rusage_t* usage);
long linux_sys_umask(int mask);
long linux_sys_prctl(int option, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
long linux_sys_gettimeofday(void* tv, void* tz);
long linux_sys_settimeofday(const void* tv, const void* tz);
long linux_sys_clock_gettime(int clk_id, void* tp);
long linux_sys_clock_settime(int clk_id, const void* tp);
long linux_sys_clock_getres(int clk_id, void* res);
long linux_sys_clock_nanosleep(int clk_id, int flags, const void* req, void* rem);
long linux_sys_timer_create(int clockid, const void* sevp, linux_timer_t* timerid);
long linux_sys_timer_settime(linux_timer_t* timerid, int flags, const void* new_value, void* old_value);
long linux_sys_timer_gettime(linux_timer_t* timerid, void* curr_value);
long linux_sys_timer_delete(linux_timer_t* timerid);
long linux_sys_nice(int inc);
long linux_sys_sched_setparam(int pid, const void* param);
long linux_sys_sched_getparam(int pid, void* param);
long linux_sys_sched_setscheduler(int pid, int policy, const void* param);
long linux_sys_sched_getscheduler(int pid);
long linux_sys_sched_get_priority_max(int policy);
long linux_sys_sched_get_priority_min(int policy);
long linux_sys_sched_setaffinity(int pid, uint64_t cpusetsize, const void* mask);
long linux_sys_sched_getaffinity(int pid, uint64_t cpusetsize, void* mask);
long linux_sys_setpriority(int which, int who, int prio);
long linux_sys_getpriority(int which, int who);
long linux_sys_mlock(const void* addr, uint64_t len);
long linux_sys_munlock(const void* addr, uint64_t len);
long linux_sys_mlockall(int flags);
long linux_sys_munlockall(void);
long linux_sys_personality(uint64_t persona);
long linux_sys_uname(void* buf);
long linux_sys_sethostname(const char* name, uint64_t len);
long linux_sys_setdomainname(const char* name, uint64_t len);
long linux_sys_getdomainname(char* name, uint64_t len);
long linux_sys_sysinfo(void* info);
long linux_sys_reboot(int magic1, int magic2, int cmd, void* arg);
long linux_sys_init_module(const void* mod_image, uint64_t len, const char* param_values);
long linux_sys_delete_module(const char* name, int flags);
long linux_sys_quotactl(int cmd, const char* special, int id, void* addr);
long linux_sys_gettid(void);
long linux_sys_set_tid_address(int* tidptr);
long linux_sys_unshare(int flags);
long linux_sys_futex(int* uaddr, int op, int val, const void* timeout, int* uaddr2, int val3);
long linux_sys_epoll_create(int size);
long linux_sys_epoll_create1(int flags);
long linux_sys_epoll_ctl(int epfd, int op, int fd, void* event);
long linux_sys_epoll_wait(int epfd, void* events, int maxevents, int timeout);
long linux_sys_epoll_pwait(int epfd, void* events, int maxevents, int timeout, const void* sigmask, uint64_t sigsetsize);
long linux_sys_inotify_init(void);
long linux_sys_inotify_init1(int flags);
long linux_sys_inotify_add_watch(int fd, const char* path, uint32_t mask);
long linux_sys_inotify_rm_watch(int fd, int wd);
long linux_sys_signalfd(int fd, const void* mask, uint64_t sigsetsize);
long linux_sys_timerfd_create(int clockid, int flags);
long linux_sys_timerfd_settime(int fd, int flags, const void* new_value, void* old_value);
long linux_sys_timerfd_gettime(int fd, void* curr_value);
long linux_sys_eventfd(int initval);
long linux_sys_eventfd2(int initval, int flags);
long linux_sys_pipe2(int* pipefd, int flags);
long linux_sys_dup3(int oldfd, int newfd, int flags);
long linux_sys_preadv(int fd, const void* iov, int iovcnt, int64_t offset);
long linux_sys_pwritev(int fd, const void* iov, int iovcnt, int64_t offset);
long linux_sys_recvmmsg(int fd, void* msgvec, uint32_t vlen, int flags, const void* timeout);
long linux_sys_sendmmsg(int fd, const void* msgvec, uint32_t vlen, int flags);
long linux_sys_process_vm_readv(int pid, const void* lvec, uint64_t liovcnt, const void* rvec, uint64_t riovcnt, uint64_t flags);
long linux_sys_process_vm_writev(int pid, const void* lvec, uint64_t liovcnt, const void* rvec, uint64_t riovcnt, uint64_t flags);
long linux_sys_kcmp(int pid1, int pid2, int type, uint64_t idx1, uint64_t idx2);
long linux_sys_memfd_create(const char* name, uint64_t flags);
long linux_sys_userfaultfd(int flags);
long linux_sys_bpf(int cmd, void* attr, uint32_t size);
long linux_sys_execveat(int dirfd, const char* pathname, char* const* argv, char* const* envp, int flags);
long linux_sys_prlimit64(int pid, int resource, const void* new_limit, void* old_limit);
long linux_sys_getrandom(void* buf, uint64_t count, uint32_t flags);
long linux_sys_membarrier(int cmd, int flags);
long linux_sys_mlock2(const void* addr, uint64_t len, int flags);
long linux_sys_copy_file_range(int fd_in, int64_t* off_in, int fd_out, int64_t* off_out, uint64_t len, uint32_t flags);
long linux_sys_preadv2(int fd, const void* iov, int iovcnt, int64_t offset, uint32_t flags);
long linux_sys_pwritev2(int fd, const void* iov, int iovcnt, int64_t offset, uint32_t flags);
long linux_sys_statx(int dirfd, const char* pathname, int flags, uint32_t mask, void* statxbuf);
long linux_sys_rseq(void* rseq, uint32_t rseq_len, int flags, uint32_t sig);
long linux_sys_pidfd_open(int pid, uint32_t flags);
long linux_sys_clone3(void* cl_args, uint64_t size);
long linux_sys_close_range(int first, int last, uint32_t flags);
long linux_sys_openat2(int dirfd, const char* pathname, void* how, uint64_t size);
long linux_sys_faccessat2(int dirfd, const char* pathname, int mode, int flags);
long linux_sys_process_madvise(int pid, const void* vec, uint64_t vlen, int advice, uint32_t flags);
long linux_sys_epoll_pwait2(int epfd, void* events, int maxevents, const void* timeout, const void* sigmask, uint64_t sigsetsize);
long linux_sys_mount_setattr(int dfd, const char* path, uint32_t flags, void* attr, uint64_t size);
long linux_sys_landlock_create_ruleset(const void* attr, uint64_t size, uint32_t flags);
long linux_sys_landlock_add_rule(int ruleset_fd, uint32_t rule_type, const void* rule_attr, uint32_t flags);
long linux_sys_landlock_restrict_self(int ruleset_fd, uint32_t flags);
long linux_sys_memfd_secret(uint32_t flags);
long linux_sys_process_mrelease(int pidfd, uint32_t flags);
long linux_sys_futex_waitv(void* waiters, uint32_t nr_futexes, uint32_t flags, const void* timeout, uint32_t clockid);
long linux_sys_set_mempolicy_home_node(uint64_t start, uint64_t len, uint64_t home_node, uint64_t flags);
long linux_sys_cachestat(int fd, const void* range, void* cstat, uint32_t flags);
long linux_sys_map_shadow_stack(uint64_t addr, uint64_t size, uint32_t flags);
long linux_sys_futex_wake(void* uaddr, uint32_t nr_wake, uint32_t flags);
long linux_sys_futex_wait(void* uaddr, uint64_t val, uint64_t mask, uint32_t flags, void* timeout, uint32_t clockid);
long linux_sys_futex_requeue(void* uaddr1, void* uaddr2, uint64_t nr_wake, uint64_t nr_requeue, uint64_t cmpval, uint32_t flags);
long linux_sys_setrlimit(int resource, const void* rlim);
long linux_sys_lseek(int fd, int64_t offset, int whence);

long linux_syscall_dispatch(uint64_t nr, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6);

#endif